name: arxiv-sota-agent
channels:
  - defaults
dependencies:
  - pandas
  - numpy
  - matplotlib
  - cryptography
  - google-cloud-aiplatform[version='>=1.130.0']
  - shapely
  - google-cloud-storage[version='>=3.7.0']
  - pip
  - grpcio
  - protobuf
  - google-cloud-bigquery-core[version='>=3.39.0']
  - google-genai[version='>=1.55.0']
  - httpx
  - python=3.12
  - tenacity
  - pydantic
  - aiohttp
  - pyyaml
  - pytest
  - tabulate
  - python-dotenv
  - tqdm
  - pypdf
  - pip:
    - docstring_parser
